### PR TITLE
Explicitly set compile and target version

### PR DESCRIPTION
**Pull request by mrmike**
- Explicitly set source and target compatibility to `1.7`. Without it you can encounter on Android

```
UNEXPECTED TOP-LEVEL EXCEPTION: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
```
- Bump version to `1.0.2`

### CODE REVIEW

**Comment by jacek-marchwicki** [comment]
@mrmike isn't also required setting compatibility for `example` and `example-model`?

thanks for contribution

**Comment by mrmike** [comment]
I've added it.

**Comment by jacek-marchwicki** [comment]
lgtm

**Comment by jacek-marchwicki** [comment]
Version 1.0.2 released ;)

**Pull request merged**
